// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "INVENTORY",
            "url": "http://localhost:8083/swagger/index.html#/",
            "email": "rohith.s@netxd.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/order/addorderdetails": {
            "post": {
                "security": [
                    {
                        "bearerToken": []
                    }
                ],
                "description": "AddOrderDetails",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "return Added Details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UpdateDetails"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.UpdateOrderResponse"
                        }
                    }
                }
            }
        },
        "/order/createorder": {
            "post": {
                "description": "createorder",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "return created order",
                "parameters": [
                    {
                        "description": "user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Orders"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Orders"
                        }
                    }
                }
            }
        },
        "/order/deletecustomer": {
            "get": {
                "security": [
                    {
                        "bearerToken": []
                    }
                ],
                "description": "DeleteCustomer Order",
                "tags": [
                    "Orders"
                ],
                "summary": "return Deleted Meassage",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.UpdateOrderResponse"
                        }
                    }
                }
            }
        },
        "/order/getbyid": {
            "get": {
                "security": [
                    {
                        "bearerToken": []
                    }
                ],
                "description": "GetById",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "return GetId",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Orders"
                        }
                    }
                }
            }
        },
        "/order/updateorder": {
            "post": {
                "security": [
                    {
                        "bearerToken": []
                    }
                ],
                "description": "UpdateOrder",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "return updated order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UpdateDetails"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.UpdateOrderResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Address": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "street1": {
                    "type": "string"
                },
                "street2": {
                    "type": "string"
                },
                "zip": {
                    "type": "string"
                }
            }
        },
        "main.Items": {
            "type": "object",
            "properties": {
                "discount": {
                    "type": "number"
                },
                "pretaxtotal": {
                    "type": "number"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "number"
                },
                "sku": {
                    "type": "string"
                },
                "tax": {
                    "type": "number"
                },
                "total": {
                    "type": "number"
                }
            }
        },
        "main.Orders": {
            "type": "object",
            "properties": {
                "carrier": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "customerid": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Items"
                    }
                },
                "payment_id": {
                    "type": "string"
                },
                "paymentstatus": {
                    "type": "string"
                },
                "shipping": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Shipping"
                    }
                },
                "status": {
                    "type": "string"
                },
                "totalamount": {
                    "type": "number"
                },
                "tracking": {
                    "type": "string"
                }
            }
        },
        "main.Origin": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "street1": {
                    "type": "string"
                },
                "street2": {
                    "type": "string"
                },
                "zip": {
                    "type": "string"
                }
            }
        },
        "main.Shipping": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Address"
                    }
                },
                "origin": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Origin"
                    }
                }
            }
        },
        "main.UpdateDetails": {
            "type": "object",
            "properties": {
                "quantity": {
                    "type": "number"
                },
                "sku": {
                    "type": "string"
                }
            }
        },
        "main.UpdateOrderResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1",
	Host:             "localhost:8089",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Documenting API (ORDER)",
	Description:      "Buy Anything In Our Webstite",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
