// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: order_proto/remove_order.proto

package ecommerce_order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoveOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId string `protobuf:"bytes,1,opt,name=CustomerId,proto3" json:"CustomerId,omitempty"`
}

func (x *RemoveOrderRequest) Reset() {
	*x = RemoveOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_remove_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOrderRequest) ProtoMessage() {}

func (x *RemoveOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_remove_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOrderRequest.ProtoReflect.Descriptor instead.
func (*RemoveOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_remove_order_proto_rawDescGZIP(), []int{0}
}

func (x *RemoveOrderRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type RemoveOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *RemoveOrderResponse) Reset() {
	*x = RemoveOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_remove_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOrderResponse) ProtoMessage() {}

func (x *RemoveOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_remove_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOrderResponse.ProtoReflect.Descriptor instead.
func (*RemoveOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_remove_order_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_order_proto_remove_order_proto protoreflect.FileDescriptor

var file_order_proto_remove_order_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a,
	0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x42, 0x30, 0x5a, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x41, 0x56, 0x41, 0x4e, 0x45, 0x45,
	0x53, 0x48, 0x4b, 0x4d, 0x2f, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x65, 0x5f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_order_proto_remove_order_proto_rawDescOnce sync.Once
	file_order_proto_remove_order_proto_rawDescData = file_order_proto_remove_order_proto_rawDesc
)

func file_order_proto_remove_order_proto_rawDescGZIP() []byte {
	file_order_proto_remove_order_proto_rawDescOnce.Do(func() {
		file_order_proto_remove_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_proto_remove_order_proto_rawDescData)
	})
	return file_order_proto_remove_order_proto_rawDescData
}

var file_order_proto_remove_order_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_order_proto_remove_order_proto_goTypes = []interface{}{
	(*RemoveOrderRequest)(nil),  // 0: order_proto.RemoveOrderRequest
	(*RemoveOrderResponse)(nil), // 1: order_proto.RemoveOrderResponse
}
var file_order_proto_remove_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_proto_remove_order_proto_init() }
func file_order_proto_remove_order_proto_init() {
	if File_order_proto_remove_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_proto_remove_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_remove_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_proto_remove_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_proto_remove_order_proto_goTypes,
		DependencyIndexes: file_order_proto_remove_order_proto_depIdxs,
		MessageInfos:      file_order_proto_remove_order_proto_msgTypes,
	}.Build()
	File_order_proto_remove_order_proto = out.File
	file_order_proto_remove_order_proto_rawDesc = nil
	file_order_proto_remove_order_proto_goTypes = nil
	file_order_proto_remove_order_proto_depIdxs = nil
}
